### ISSUE TITLE
Tests using U+D800 to U+DFFF

### ISSUE THREAD

**Issue by waisbrot** [jmespath/jmespath.test#3]
I notice there are some tests that ask the library to encode Unicode values in the UTF-16 surrogate range. ([example](https://github.com/jmespath/jmespath.test/blob/master/tests/identifiers.json#L1366-L1376))

I don't know much about Unicode but my [crude understanding](http://en.wikipedia.org/wiki/UTF-16#U.2BD800_to_U.2BDFFF) is that this should be an invalid range for encoding. Is the JMESPath spec including these values because it specifically wants to work with them? (I'm working with a library that refuses to encode those values based on the spec and wondering if I need to hack around my library or if I can convince you to modify the JMESPath spec.)

**Comment by jamesls** [comment]
That test was taken from the [JSON RFC](https://tools.ietf.org/html/rfc7159#page-9), Section 7:

> To escape an extended character that is not in the Basic Multilingual
>    Plane, the character is represented as a 12-character sequence,
>    encoding the UTF-16 surrogate pair.  So, for example, a string
>    containing only the G clef character (U+1D11E) may be represented as
>    "\uD834\uDD1E".

So in this case, we're not trying to encode the individual code points (which as you mention would be invalid) but instead we're parsing both of those as a surrogate pair to get the final U+1D11E value.

Can you share what library your using that's giving you issues?  I'm curious.

**Comment by waisbrot** [comment]
Ah! Thanks for explaining. I'm calling Erlang's [`unicode:characters_to_binary/1`](http://www.erlang.org/doc/man/unicode.html#characters_to_binary-1) and getting back an error when I try to encode those values. 

However, I believe the problem is that I'm asking to encode them as two individual characters instead of together as one. I'll try again now that I've got a better handle on what's going on.

**Comment by waisbrot** [comment]
For the curious: I was trying to do `unicode:characters_to_binary("\x{d800}\x{d800}")` and it seems like Erlang looks at the individual characters in the string and rejects them as illegal. For the moment, I'm copying [the code in jsx](https://github.com/talentdeficit/jsx/blob/develop/src/jsx_decoder.erl#L754-L757) (the JSON library I'm using), which handles the surrogates manually. I suspect it's doing that because it predates Erlang's deciding to actually support Unicode, but I haven't found an example of doing what I want more easily.
