### ISSUE TITLE
Invalid benchmark expressions

### ISSUE THREAD

**Issue by robertmrk** [jmespath/jmespath.test#8]
First of all, thanks @jamesls for creating this great little query language and the detailed specifications! 

I liked the various implementations of JMESPath so much, that I decided I wan't to use it in C++ too, so I created [my own implementation](https://github.com/robertmrk/jmespath.cpp). The library is nearly finished, I just need to get some packaging code in place and improve the user documentation.
It runs all the compliance tests except the benchmarks. The problem is that `benchmarks.json` contains two expressions which according to the current specifications are invalid.
The first one is: `sum(z, y, x, w, v, u, t, s, r, q, p, o, n, m, l, k, j, i, h, g, f, e, d, c, b, a)`, the specifications of the [sum function](http://jmespath.org/specification.html#sum) says it should accept only a signle array argument.
The second one is: `foo[bar > baz][qux > baz]`, but [filter expressions](http://jmespath.org/specification.html#filter-expressions) should start with `[?`.

I'm not sure if these tests made it into `benchmarks.json` by error (in which case I will create a PR to fix the tests), or if they are written for some yet unreleased version of the specifications?

**Comment by jamesls** [comment]
Thanks for catching these.

I've added a fix for these: https://github.com/jmespath/jmespath.test/pull/11

**Comment by jamesls** [comment]
Fixed via #11

**Comment by robertmrk** [comment]
Thank you very much for fixing this issue!
